[package]
name = "reset"
version = "0.1.0"
edition = "2021"
description = "A wip universal Linux settings application."

[dependencies]
adw = { version = "0.5.3", package = "libadwaita", features = ["v1_4"]}
dbus = "0.9.7"
gtk = { version = "0.7.3", package = "gtk4", features = ["v4_12"]}

[build-dependencies]
glib-build-tools = "0.18.0"
