[package]
name = "reset"
version = "0.1.0"
edition = "2021"
description = "A wip universal Linux settings application."

[dependencies]
ReSet-Lib = "*"
adw = { version = "*", package = "libadwaita", features = ["v1_4"]}
gtk = { version = "*", package = "gtk4"}

[build-dependencies]
glib-build-tools = "*"
