on:
  release:
    types: [created]
jobs:
  release:
    runs-on: [self-hosted, ubuntu]
    steps:
      - uses: actions/checkout@v3
      - name: nightly-rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - name: Build rust package
        run: |
          cargo build --release --verbose
      - name: Build Flatpak
        run: "cd flatpak\npython3 flatpak-generator.py ../Cargo.lock -o cargo-sources.json \nflatpak-builder build org.Xetibo.ReSet.json --force-clean \nflatpak build-export export build\nflatpak build-bundle export reset.flatpak org.Xetibo.ReSet\n"
      - name: Build Ubuntu package
        run: |
          mkdir -p ./debian/usr
          mkdir -p ./debian/usr/bin
          mkdir -p ./debian/usr/share
          mkdir -p ./debian/usr/share/applications
          mkdir -p ./debian/usr/share/pixmaps
          cp ./target/release/ReSet ./debian/usr/bin/ReSet
          cp ./ReSet.desktop ./debian/usr/share/applications/.
          cp ./src/resources/icons/ReSet.svg ./debian/usr/share/pixmaps/.
          dpkg-deb --build debian
          mv debian.deb ReSet.deb
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/ReSet
            flatpak/reset.flatpak
            ReSet.deb
