on:
  release:
    types: [ created ]

jobs:
  release:
    runs-on: [self-hosted, ubuntu]
    steps:
      - uses: actions/checkout@v3
      - name: nightly-rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - name: Build rust package
        run: cargo build --release --verbose
      - name: Build Flatpak
        run: |
          cd flatpak
          python3 flatpak-generator.py ../Cargo.lock -o cargo-sources.json 
          flatpak-builder build org.xetibo.ReSet.json --force-clean 
          flatpak build-export export build
          flatpak build-bundle export reset.flatpak org.xetibo.ReSet
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/reset
            flatpak/reset.flatpak
