on:
  release:
    types: [created]
jobs:
  release:
    runs-on: [self-hosted, ubuntu]
    steps:
      - uses: actions/checkout@v3
      - name: nightly-rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - name: Build rust package
        run: cargo build --release --verbose
      - name: Build Flatpak
        run: "cd flatpak\npython3 flatpak-generator.py ../Cargo.lock -o cargo-sources.json \nflatpak-builder build org.Xetibo.ReSet.json --force-clean \nflatpak build-export export build\nflatpak build-bundle export reset.flatpak org.Xetibo.ReSet\n"
      - name: Build Ubuntu package
        run: |
          cp ./target/release/reset ./debian/usr/bin/.
          cp ./reset.desktop ./debian/share/applications/.
          cp ./src/resources/icons/ReSet.svg ./debian/share/pixmaps/.
          dpkg-deb --build debian
          mv debian.deb reset.deb
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/reset
            flatpak/reset.flatpak
            reset.deb
